FROM postgres:15.5-alpine

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD db_startup.sh /docker-entrypoint-initdb.d/
ADD postgres_password /docker-entrypoint-initdb.d/

ADD init.sql /tmp/