FROM python:3.8

COPY ./api/requirements.txt /usr/src/api/requirements.txt

RUN pip3 install --upgrade pip

RUN pip3 install -r /usr/src/api/requirements.txt

WORKDIR /usr/src/

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]